[package]
name = "tsumeshogi"
version = "0.1.0"
authors = ["na2hiro <a@81.la>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shogi = "0.9.0"